# Generated by Django 4.2.10 on 2024-04-07 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_kategori_alter_product_price_product_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField(default=1, verbose_name='Adet')),
                ('toplam', models.IntegerField(null=True, verbose_name='Toplam Tutar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sepete Ekleyen')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Eklenen Üürn')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Sepetteki Ürünler',
            },
        ),
    ]
