# Generated by Django 4.2.10 on 2024-04-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sepet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sepet',
        ),
    ]
