# Generated by Django 4.2.10 on 2024-04-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Eklenen Ürün'),
        ),
    ]
