# Generated by Django 4.2.10 on 2024-04-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_sepet_urun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sepet',
            options={},
        ),
        migrations.RenameField(
            model_name='sepet',
            old_name='alici',
            new_name='kullanıcı',
        ),
        migrations.RenameField(
            model_name='sepet',
            old_name='created_at',
            new_name='satinAlmaTarihi',
        ),
        migrations.RemoveField(
            model_name='sepet',
            name='toplam',
        ),
        migrations.RemoveField(
            model_name='sepet',
            name='updated_at',
        ),
    ]
