# Generated by Django 4.2.10 on 2024-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_sepet_options_rename_alici_sepet_kullanıcı_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='toplam',
            field=models.IntegerField(null=True, verbose_name='Toplam Tutar'),
        ),
    ]
