# Generated by Django 4.2.10 on 2024-04-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sepet_toplam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepet',
            name='toplam',
        ),
    ]
